site_name: Locus Game Engine
theme:
  palette:
    scheme: locus
    primary: custom
  name: material
  logo: 'Resources/LocusLogoIcon.png'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
  font:
    text: Inter
  favicon: img/logo.ico

repo_url: https://github.com/Kyenel64/Locus-Engine
repo_name: Locus-Engine

extra_css:
  - stylesheet/extra.css

extra:
  analytics:
    provider: google
    property: G-QHSJC6QMQX


# page tree
nav:
  - Home: index.md
  - Getting Started:
    - Introduction: Pages/GettingStarted/Introduction.md
    - How to Build: Pages/GettingStarted/HowToBuild.md
  - Documentation:
    - Introduction: Pages/Documentation/Introduction.md
    - Workflow: Pages/Documentation/Workflow.md
    - Classes:
      - CircleCollider2DComponent: Pages/Documentation/Classes/CircleCollider2DComponent.md
      - CircleRendererComponent: Pages/Documentation/Classes/CircleRendererComponent.md
      - Color: Pages/Documentation/Classes/Color.md
      - Component: Pages/Documentation/Classes/Component.md
      - Entity: Pages/Documentation/Classes/Entity.md
      - Input: Pages/Documentation/Classes/Input.md
      - Mat4: Pages/Documentation/Classes/Mat4.md
      - Rigidbody2DComponent: Pages/Documentation/Classes/Rigidbody2DComponent.md
      - SpriteRendererComponent: Pages/Documentation/Classes/SpriteRendererComponent.md
      - TransformComponent: Pages/Documentation/Classes/TransformComponent.md
      - Vec2: Pages/Documentation/Classes/Vec2.md
      - Vec3: Pages/Documentation/Classes/Vec3.md
      - Vec4: Pages/Documentation/Classes/Vec4.md
    - Enums:
      - KeyCode: Pages/Documentation/Enums/KeyCode.md
      - RigidbodyType: Pages/Documentation/Enums/RigidbodyType.md