site_name: Locus Game Engine
theme:
  palette:
    scheme: locus
    primary: custom
  name: material
  logo: 'Resources/LocusLogo_Border.png'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.top
  custom_dir: docs/Custom/
  font:
    text: Inter
  favicon: img/logo.ico

repo_url: https://github.com/Kyenel64/Locus-Engine
repo_name: Locus-Engine

extra_css:
  - stylesheet/extra.css

extra:
  analytics:
    provider: google
    property: G-QHSJC6QMQX


# page tree
nav:
  - Home: index.md
  - About:
    - Introduction: Pages/About/Introduction.md
  - Getting Started:
    - Introduction: Pages/GettingStarted/Introduction.md
    - How to Build: Pages/GettingStarted/HowToBuild.md
    - Workflow: Pages/GettingStarted/Workflow.md
    - Example Project - Solar System: Pages/GettingStarted/ExampleProject_SolarSystem.md
  - Documentation:
    - Introduction: Pages/Documentation/Introduction.md
    - Classes:
      - Component: Pages/Documentation/Classes/Component.md
      - Entity: Pages/Documentation/Classes/Entity.md
      - Vec3: Pages/Documentation/Classes/Vec3.md