site_name: Locus Game Engine
theme:
  palette:
    scheme: slate
    primary: custom
  name: material
  logo: 'Resources/LocusLogo_Border.png'
  features:
    - navigation.tabs
  custom_dir: docs/Custom/
  font:
    text: Inter
  favicon: img/logo.ico

repo_url: https://github.com/Kyenel64/Locus-Engine
repo_name: Locus-Engine

extra_css:
  - stylesheets/extra.css


# page tree
nav:
  - Home: index.md
  - About:
    - Introduction: About/Introduction.md
  - Getting Started:
    - Introduction: Getting_Started/Introduction.md
    - How to Build: Getting_Started/HowToBuild.md
    - Workflow: Getting_Started/Workflow.md
    - Example Project - Solar System: Getting_Started/ExampleProject_SolarSystem.md
  - Documentation: Documentation/Documentation.md