site_name: Locus Game Engine
theme:
  palette:
    scheme: slate
    primary: custom
  name: material
  logo: 'Resources/LocusLogo_Border.png'
  features:
    - navigation.instant
    - navigation.instant.progress
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
  custom_dir: docs/Custom/
  font:
    text: Inter
  favicon: img/logo.ico

repo_url: https://github.com/Kyenel64/Locus-Engine
repo_name: Locus-Engine

extra_css:
  - assets/css/extra.css

extra:
  analytics:
    provider: google
    property: G-QHSJC6QMQX


# page tree
nav:
  - Home: index.md
  - About:
    - Introduction: About/Introduction.md
  - Getting Started:
    - Introduction: Getting_Started/Introduction.md
    - How to Build: Getting_Started/HowToBuild.md
    - Workflow: Getting_Started/Workflow.md
    - Example Project - Solar System: Getting_Started/ExampleProject_SolarSystem.md
  - Documentation:
    - Introduction: Documentation/Introduction.md
    - Classes:
      - Component: Documentation/Classes/Component.md
      - Entity: Documentation/Classes/Entity.md
      - Vec3: Documentation/Classes/Vec3.md